<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BusBooking.Domain\BusBooking.Domain.csproj" />
    <ProjectReference Include="..\BusBooking.Infrastructure\BusBooking.Infrastructure.csproj" />
    <ProjectReference Include="..\BusBooking.Shared\BusBooking.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
